"""add column created_by in tb_transaksi

Revision ID: 3603c2068b5e
Revises: dceebf3333bc
Create Date: 2023-02-17 23:19:27.593222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3603c2068b5e'
down_revision = 'dceebf3333bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaksi', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
