"""change data nullable=True in tb_user

Revision ID: a6246e97d025
Revises: b99b8513827f
Create Date: 2023-01-31 06:59:26.875767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6246e97d025'
down_revision = 'b99b8513827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
