"""add tb_chat

Revision ID: b8c4da47f6e3
Revises: 8d73767a6ad2
Create Date: 2023-02-01 00:27:38.926885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c4da47f6e3'
down_revision = '8d73767a6ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_produk', sa.String(), nullable=False),
    sa.Column('from_chat', sa.String(), nullable=False),
    sa.Column('to_chat', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_chat')
    # ### end Alembic commands ###
