"""add unique=true in User.username

Revision ID: bb72c7e7e0dc
Revises: 
Create Date: 2023-01-31 12:00:36.201027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb72c7e7e0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_produk', sa.Integer(), nullable=False),
    sa.Column('jenis_produk', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_produk')
    )
    op.create_table('tb_transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resi', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    op.drop_table('tb_transaksi')
    op.drop_table('tb_produk')
    # ### end Alembic commands ###
