"""add column created_by in tb_product

Revision ID: dceebf3333bc
Revises: b8c4da47f6e3
Create Date: 2023-02-06 08:06:49.662342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceebf3333bc'
down_revision = 'b8c4da47f6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produk', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
